### ISSUE TITLE
Privacy provider implementation in the wrong location

### ISSUE THREAD

**Issue by volodymyrdovhan** [TUL-ELC/qbank_filtername#1]
Hello,
the Privacy provider folder/class should be in the '`/classes`' folder.
Currently, Moodle cannot find the definition in a plugin root directory.

![image](https://github.com/user-attachments/assets/c0694d9b-1c8b-4b7b-9f63-6a09a84867ee)
![image](https://github.com/user-attachments/assets/a13e7542-40d8-4c3d-919d-d693fda9cad1)

**Comment by TUL-ELC** [comment]
Hello,
Privacy provider has been moved to classes directory. We verified the proper functioning of the privacy provider using the admin tool dataprivacy.
Sorry for the mistake.
