### ISSUE TITLE
Incorrect repository name

### ISSUE THREAD

**Issue by volodymyrdovhan** [TUL-ELC/qbank_filtername#2]
Hello,
based on the naming convention for Moodle plugins, the repository name should match the pattern: moodle-{plugintype}_{pluginname}.

This is not a strong requirement, just an option to provide a consistent experience for other Moodle developers.

**Comment by TUL-ELC** [comment]
Hello,
The repository name was changed to **moodle-qbank_filtername** to match the naming convention.
